import pyautogui
import os, sys, time
import random
pyautogui.FAILSAFE= False

lst = [1, 2, 3, 4, 5,]
lst2 = [13, 21, 27, 39, 46, 53]
lst3 = [3, 4, 5, 6, 7]
 
def mouse():
    rand1 = random.choice(lst)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click( )
    time.sleep(rand1)

def key_1():
    rand1 = random.choice(lst)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    
def mouse_2():
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)

def key_2():
    rand1 = random.choice(lst)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)

def mouse_3():
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)

def key_3():
    rand1 = random.choice(lst)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    rand2 = random.choice(lst2)
    time.sleep(rand2)

def mouse11():
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()

def key_11():
    rand1 = random.choice(lst)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("f5")
    time.sleep(rand1)

def mouse_12():
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)

def key_12():
    rand1 = random.choice(lst)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("f5")
    time.sleep(rand1)
    
def mouse_13():
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(150, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(400, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(650, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(900, 10, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1150, 11, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    rand1 = random.choice(lst)
    pyautogui.moveTo(1400, 12, duration=1)
    pyautogui.click()
    time.sleep(rand1)
    
def key_13():
    rand1 = random.choice(lst)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pageup")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    rand1 = random.choice(lst)
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("pagedown")
    time.sleep(rand1)
    pyautogui.press("f5")
    rand2 = random.choice(lst2)
    time.sleep(rand2)
try:
    while True:
        mouse()
        mouse()
        key_1()
        mouse_2()
        mouse_2()
        key_2()
        mouse_3()
        mouse_3()
        key_3()
        mouse11()
        mouse11()
        key_11()
        mouse_12()
        mouse_12()
        key_12()
        mouse_13()
        mouse_13()
        key_13()
except KeyboardInterrput:
    print('\n')
